### PR TITLE
docs: update script location.

### PR DESCRIPTION
**Pull request by zbwright**

### CODE REVIEW

**Comment by zbwright** [comment]
TIL editing through the github browser interface does not allow me to add a reviewer or a do-not-test label. @alekssaul @ElijahCaine

**Comment by alekssaul** [comment]
this looks good to me.. Can we confirm this will only effect 1.6, documentation?

**Comment by zbwright** [comment]
@joshix and @ElijahCaine are working on a sync for other changes to the Matchbox doc. They'll be able to answer this.

**Comment by dghubble** [comment]
This conflicts with the source location in the repo. I talked with Redbeard about the next matchbox release placing the script in examples/etc/matchbox to match source.

**Comment by zbwright** [comment]
ah. how far out it the next release? should we hold off on this edit?

**Comment by dghubble** [comment]
We could do a patch release next week.

**Comment by zbwright** [comment]
ok. @alekssaul @dghubble I think, because most users will *not* use this feature, and because those who do can probably figure out the solution, and because it will be fixed Wednesday, I vote not updating the doc.

what say ye?

**Comment by alekssaul** [comment]
That sounds fair, I'd recommend keeping the issue in the tectonic-installer repo open in case a user stumbles upon it.

**Comment by zbwright** [comment]
cool. I'm going to close this PR, and you two will manage the other bits. thanks.

**Pull request closed without merging**
