### PR TITLE
examples: Update self-hosted Kubernetes to v1.5.4

### PR DESCRIPTION
**Pull request by dghubble**
* Upgrade to self-hosted Kubernetes v1.5.4
* Use bootkube v0.3.10
* Disable anonymous-auth flag for on-host kubelet
* Set the client CA for the on-host kubelet, based on the kubeconfig

### CODE REVIEW

**Comment by aaronlevy** [comment]
v0.3.10 doesn't contain v1.5.4. There might not be any problems here, but technically your kubelets shouldn't be a higher version than your control-plane.

I will be cutting another bootkube release shortly which does contain v1.5.4

**Comment by dghubble** [comment]
Planning for the future :sparkles:

**Comment by dghubble** [comment]
The :sparkles: future :sparkles:  has arrived.

**Comment by aaronlevy** [comment]
lgtm. I kinda like the execStartPre approach -- may incorporate that into bootkube.

**Comment by dghubble** [comment]
Props to @ericchiang for that one

**Pull request merged**
