### PR TITLE
Adds documentation for using a Squid proxy with Matchbox.

### PR DESCRIPTION
**Pull request by danehans**
This PR closes https://github.com/coreos/matchbox/issues/297

### CODE REVIEW

**Comment by ndouglas** [comment]
I think I'll need to go back through and test this in greater depth, perhaps later today or tomorrow.

Briefly:
Your instructions are very clear and explain the setup very well.

I'm running Squid with a manual command (basically copied and pasted from your service definition, but with the path to squid.conf updated appropriately) on a clean + docker + docker-compose installation of Debian Jessie in a pretty simple VM running on ESXi 6.5.  The iptables rules were applied.  My DHCP is provided by pfSense, and my group definition was updated and the client boots and is pointed to the correct URL.  It times out, though, on retrieving the kernel.

The issue seems to be with the Squid configuration -- it doesn't seem to be actively listening or opening the port.  Telnetting to either :80 or :3128 from the local machine fails.  I see a repeated error when running the container in the foreground:

`2017/03/09 23:04:28| ERROR: No forward-proxy ports configured.`

This is probably PEBKAC on my part, but I wanted to mention it before doing more in-depth (and careful!) testing tomorrow, just in case it rang any bells.  I'm not very knowledgeable about Squid, so if this points clearly to an obvious issue, that's why I'm missing it.  I might just need to add a port or something to the config.

I also have CentOS and CoreOS VMs handy, and I can whip anything else up pretty easily if you have any suggestions.

**Comment by danehans** [comment]
@ndouglas make sure you have this line in your squid.conf file:

`http_port 3128 intercept`

In my example, I am using the `--net=host` flag so the squid container uses the host's netns. I can netstat the port and see it used by the squid container:

`$ sudo netstat -tulpn | grep 3128
tcp        0      0 0.0.0.0:3128            0.0.0.0:*               LISTEN      6482/squid3  `

Verify your firewalld/iptables settings. My setup uses firewalld:
```
$ sudo firewall-cmd --get-active-zones
internal
  interfaces: enp14s0
public
  interfaces: enp15s0

$ sudo firewall-cmd --zone=internal --list-all
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp14s0
  sources: 
  services: dhcp dhcpv6-client dns ipp-client mdns samba-client ssh tftp
  ports: 3128/tcp 4080/tcp 8888/tcp 67/udp 53/udp 3129/tcp 8080-8082/tcp
  protocols: 
  masquerade: no
  forward-ports: port=80:proto=tcp:toport=3128:toaddr=10.30.118.164
	port=80:proto=tcp:toport=3128:toaddr=10.10.129.133
  sourceports: 
  icmp-blocks: 
  rich rules: 
```

Although I opened 3129 in the example above, I am only using TCP port 3128 for squid. You may also want to try running standard squid proxy on port 3128 and transparent proxy on 3129. Here is the squid.conf settings:
```
http_port 3128
http_port 3129 transparent
```

Good luck and let me know how it goes.

**Comment by dghubble** [comment]
Thanks! Looks great, I'll try to find some time to vet this and use it for real and add onto it if that's alright.

I'd like a usage section to show rkt and docker one-liners and to fold the configs and systemd units into a contrib directory and expand on how networked nodes or individual nodes are configured to use the proxy. Also, these docs now get published to [coreos.com](https://coreos.com/matchbox/docs/latest) so I'll figure out where they fit in.

**Comment by danehans** [comment]
Sounds good. I'll try to do another round of vetting myself.

**Comment by dghubble** [comment]
I haven't had the time I had hoped. Let's merge these as drafts in `contrib/squid` (see #510) so we can use #511 to track iterative improvements toward being sync'd to the docs site.

**Pull request closed without merging**
