### PR TITLE
examples: Use Kubernetes on-host etcd TLS

### LINKED ISSUE #565: Enable Kubernetes on-host etcd TLS
Bootkube added etcd TLS support in v0.4.1. https://github.com/kubernetes-incubator/bootkube/pull/433

- [x] Manual Kubernetes (bootkube) cluster
- [x] Terraform-based Kubernetes (bootkube) cluster

For self-hosted etcd TLS, see #262

### PR DESCRIPTION
**Pull request by dghubble**
Matchbox Kubernetes cluster examples/modules now enable on-host etcd TLS always - there is not option to turn it off. Kubernetes clusters can now **finally!** be deployed in networks alongside untrusted servers. etcd TLS for experimental self-hosted etcd is tracked in #262.

* Require etcd3 cluster peers to use TLS to secure communication channels and require clients to be authenticated with a TLS client certificate
* kube-apiserver (including bootstrap) communicates with TLS authenticated on-host etcd cluster
* Configure locksmith to speak directly to an etcd nodes. Stop running an etcd gateway on workers.

Checked

* Tested (manual) bootkube example
* Tested (manual) bootkube-install example to ensure locksmithd coordinates auto-updates
* Tested (terraform) bootkube-install example

cc @diegs
Closes #565

### CODE REVIEW

**Comment by dghubble** [comment]
Chatting with @diegs, bootkube renders separate etcd client and peer TLS certificates. We may want to use the peer certs for etcd peers and the client one for locksmith and kubelet.

**Comment by dghubble** [comment]
@diegs Using the etcd-peer.crt/key for etcd peers. Using the etcd-client.crt/key for locksmithd, bootstrap-apiserver, and kube-apiserver.

**Comment by dghubble** [comment]
These clusters bootstrap successfully. Still investigating one issue accessing the apiserver after the pivot.

**Comment by diegs** [comment]
Dcoumenting our discussion: the etcd certs need to be added to `assets/manifests/kube-apiserver-secrets.yaml`

**Comment by dghubble** [comment]
Added in https://github.com/dghubble/bootkube-terraform/commit/21131aa65e371389fda72a93b86b59a84aa01c1b, I missed that diffing the base64'd contents.

The issue was present only on the terraform-based cluster, but I've tested its resolved now.

**Comment by dghubble** [comment]
Deployed a prod cluster earlier - its been running fine and auto-updated to 1353.8.0.

**Pull request merged**
