### PR TITLE
variables have to be exported

### PR DESCRIPTION
**Pull request by celevra**

### CODE REVIEW

**Comment by dghubble** [comment]
This shouldn't be needed

**Comment by celevra** [comment]
In bash its needed
Only if you put it infront of the command, you can use it without export


<http://www.9folders.com/>
________________________________
Von: Dalton Hubble <notifications@github.com>
Gesendet: 17.07.2017 18:43
An: coreos/matchbox
Cc: Philipp Zeitschel; Author
Betreff: Re: [coreos/matchbox] variables have to be exported (#610)


This shouldn't be needed

-

**Comment by celevra** [comment]
Kubectl is a subprocess and can't read my variables

https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export

<http://www.9folders.com/>
________________________________
Von: Dalton Hubble <notifications@github.com>
Gesendet: 17.07.2017 18:43
An: coreos/matchbox
Cc: Philipp Zeitschel; Author
Betreff: Re: [coreos/matchbox] variables have to be exported (#610)


This shouldn't be needed

-

**Comment by dghubble** [comment]
Sure, looks like the local env is setup differently to not require this. Can you update this throughout the docs?

**Comment by dghubble** [comment]
See #613

**Pull request closed without merging**
