### PR TITLE
Add generic to gRPC

### PR DESCRIPTION
**Pull request by trunet**
To make terraform-provider-matchbox works with kickstart templates (https://github.com/coreos/matchbox/issues/224), we need generic on gRPC.

This is also needed for https://github.com/coreos/terraform-provider-matchbox/issues/16

### CODE REVIEW

**Comment by dghubble** [comment]
Yes, adding generic templates into the gRPC API alongside Container Linux configs is in-scope to provide this functionality to gRPC clients. I've added an issue at https://github.com/coreos/matchbox/issues/562.

**Comment by dghubble** [comment]
Please squash and follow the commit message format. Also, I think if you run `make codegen` the diff is slightly different. Its nice you've updated the bootcmd example client (although we don't ship it currently), thanks.

How have you tested?

```sh
./bin/bootcmd --endpoints matchbox.example.com:8081 generic create -f arbitrary.thing
Error:  rpc error: code = Unimplemented desc = unknown service rpcpb.Generic
```

You'll need to register the server in `grpc.go`

**Comment by dghubble** [comment]
Closes #562 once complete

**Comment by trunet** [comment]
I didn't test trough the bootcmd, I tested straight on the terraform-matchbox plugin with the changes I made. I will send the terraform PR soon as I have this merged. I'm sending the squash commit.

**Comment by dghubble** [comment]
Squashing refers to (rebasing and) squashing changes into one commit.

**Comment by trunet** [comment]
sorry, I made a merge before pushing the squash. just fixed.

**Comment by dghubble** [comment]
Thanks, LGTM. 

Small note, generally when you do a feature branch and rebase/squash, you should not end up with a merge "bubble" so the proposed changes are on top. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html This will merge as https://github.com/coreos/matchbox/tree/add-generic

**Pull request closed without merging**
